In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("DataCoSupplyChainDataset.csv",encoding = 'latin-1')
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,02-03-2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99998 entries, 0 to 99997
Data columns (total 53 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Type                           99998 non-null  object
 1   Days for shipping (real)       99998 non-null  int64
 2   Days for shipment (scheduled)  99998 non-null  int64
 3   Benefit per order              99998 non-null  float64
 4   Sales per customer             99998 non-null  float64
 5   Delivery Status                99998 non-null  object
 6   Late_delivery_risk             99998 non-null  int64
 7   Category Id                    99998 non-null  int64
 8   Category Name                  99998 non-null  object
 9   Customer City                  99998 non-null  object
 10  Customer Country               99998 non-null  object
 11  Customer Email                 99998 non-null  object
 12  Customer Fname                 99998 non-null  object
 13  Customer Id                    99998 non-null  int64
 14  Customer Lname                 99993 non-null  object
 15  Customer Password              99998 non-null  object
 16  Customer Segment               99998 non-null  object
 17  Customer State                 99998 non-null  object
 18  Customer Street                99998 non-null  object
 19  Customer Zipcode               99995 non-null  float64
 20  Department Id                  99998 non-null  int64
 21  Department Name                99998 non-null  object
 22  Latitude                       99998 non-null  float64
 23  Longitude                      99998 non-null  float64
 24  Market                         99998 non-null  object
 25  Order City                     99998 non-null  object
 26  Order Country                  99998 non-null  object
 27  Order Customer Id              99998 non-null  int64
 28  order date (DateOrders)        99998 non-null  object
 29  Order Id                       99998 non-null  int64
 30  Order Item Cardprod Id         99998 non-null  int64
 31  Order Item Discount            99998 non-null  float64
 32  Order Item Discount Rate       99998 non-null  float64
 33  Order Item Id                  99998 non-null  int64
 34  Order Item Product Price       99998 non-null  float64
 35  Order Item Profit Ratio        99998 non-null  float64
 36  Order Item Quantity            99998 non-null  int64
 37  Sales                          99998 non-null  float64
 38  Order Item Total               99998 non-null  float64
 39  Order Profit Per Order         99998 non-null  float64
 40  Order Region                   99998 non-null  object
 41  Order State                    99998 non-null  object
 42  Order Status                   99998 non-null  object
 43  Order Zipcode                  13783 non-null  float64
 44  Product Card Id                99998 non-null  int64
 45  Product Category Id            99998 non-null  int64
 46  Product Description            0 non-null      float64
 47  Product Image                  99998 non-null  object
 48  Product Name                   99998 non-null  object
 49  Product Price                  99998 non-null  float64
 50  Product Status                 99998 non-null  int64
 51  shipping date (DateOrders)     99998 non-null  object
 52  Shipping Mode                  99998 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 40.4+ MB

In [4]:
df.isnull().sum()

Type                                 0
Days for shipping (real)             0
Days for shipment (scheduled)        0
Benefit per order                    0
Sales per customer                   0
Delivery Status                      0
Late_delivery_risk                   0
Category Id                          0
Category Name                        0
Customer City                        0
Customer Country                     0
Customer Email                       0
Customer Fname                       0
Customer Id                          0
Customer Lname                       5
Customer Password                    0
Customer Segment                     0
Customer State                       0
Customer Street                      0
Customer Zipcode                     3
Department Id                        0
Department Name                      0
Latitude                             0
Longitude                            0
Market                               0
Order City                           0
Order Country                        0
Order Customer Id                    0
order date (DateOrders)              0
Order Id                             0
Order Item Cardprod Id               0
Order Item Discount                  0
Order Item Discount Rate             0
Order Item Id                        0
Order Item Product Price             0
Order Item Profit Ratio              0
Order Item Quantity                  0
Sales                                0
Order Item Total                     0
Order Profit Per Order               0
Order Region                         0
Order State                          0
Order Status                         0
Order Zipcode                    86215
Product Card Id                      0
Product Category Id                  0
Product Description              99998
Product Image                        0
Product Name                         0
Product Price                        0
Product Status                       0
shipping date (DateOrders)           0
Shipping Mode                        0
dtype: int64

In [9]:
df_base = df[['Order Item Total', 'Shipping Mode']]